database:
  host: ENC[AES256_GCM,data:Cq3hRVHhdDO+,iv:kwEclM7yf6I0r8JAGFv5rR+U/HJTeAcjjJuY1fy4ISI=,tag:h/f1s1ICmsYL6RirkYXa1w==,type:str]
  port: ENC[AES256_GCM,data:zVUxvg==,iv:BB3i6ucvG24dD7djl+EFj3O9KV647ECox4ZhiZAZ7zA=,tag:JW71/D8KDM0Bpy4GTIWuvg==,type:int]
  username: ENC[AES256_GCM,data:PvlqObKw,iv:QKxpbEBnipEX4VJaZxz5kn+hjJZ22G4WnjywmokfdJ8=,tag:bKWxK++91oLjeV9f/mMRvA==,type:str]
  password: ENC[AES256_GCM,data:fsRclkf+LhUBfBGDC37Bsj9JE8AG,iv:R/RABKVL4V3VnEMizDnu9/sbYFeruynWWcWVMVHFldo=,tag:M643DvZk/bqUZSI7zqPq6w==,type:str]
api:
  key: ENC[AES256_GCM,data:x80Y6/ykZnTHvTdTqg==,iv:63iS1tGjg+ZGdAKMX0eyLHSsfM0fCncqMFOZoHi2D5U=,tag:fURvKhe9XOrMoki38o5ZFw==,type:str]
  secret: ENC[AES256_GCM,data:TwlVHzULiowzMIUlrcMrMw==,iv:u+ciy2ajM+hOnP1QohDkfDSAPqJtiVQ7XjqQv8RateE=,tag:kFMruU43jCgX/WjPHOa92Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaHVYd1BkRTJaU0VKRG5j
        bnhxMTk3dFYzZFhocXNXQ0lndmQyeTVHSTM0CjVuTkFMZFIwRGlOS2M5dzdnTktQ
        NW9lZ2lRbDB4SlA1TGRtdVRRUDd6d1kKLS0tIDdkUHFOYVg2OWVRNE42YnFSZ3FP
        Z21qUGZHRytjOEJwSVFOVTNqK2dVVTAKlUaKrypgGhvpPQejCW0tusklSojap5tP
        ISDWaSHkGqOyPhxo6LX190ZnpEmxFb+KySdpbXyb4SkjnUcIgjL/ug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jq7hcntklunzhpdr99lnf0sr93kafkww3qe5ycc70xj7yp8uu94q27rwld
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UUJ4Rk8rSy9ISW1VeU44
        OGNSOU0zaFUzcTZHRVlDZUxXZGszWDhCdG0wCnd4cnU1a3ZzUTVOZkhzWmVEWW1T
        dFB2dnZYL2kwYTB6MFI3MUE5V1N2SFUKLS0tIFhYcExjOGJTVWdDbzluZWNYNUJV
        UjliWTFkWEQ3VUo3OGdqa3JJMWlhVzQKFdpB/eV9RpjJvolEG/vS7xnw4pMwJhWh
        waTPndDHcBpi6fsSUybw32+VegPX5GcDgD6AzNaJQBdHgFfJUPucrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ru40cegpzhhj7wp9kg6x8kur9e3k65cyenehtczl99xkhz06w9lssren5d
  lastmodified: "2026-05-17T11:22:26Z"
  mac: ENC[AES256_GCM,data:mRav8jBjRIQvfa4uOnJHTW6iPtcKBEjTqJ9SqCUqbDJqgv9hC7H4EFUCUIwRoKWC4z388F3wdC1rI4DHILvArED/MvslucT8qfIZJl/kLOH7suP1KZKfopE7d7u/cUjaAnMU/rNfpj5/YhLiSOWnHNHBiAdyOWr76SfXwyLtAdU=,iv:Sq4M6NPJaLyjWX5is0SKJibdR5uOU8invitvbra8PuY=,tag:T1jlMUxQyERslREhxoSSyw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
