database:
    host: ENC[AES256_GCM,data:Cq3hRVHhdDO+,iv:kwEclM7yf6I0r8JAGFv5rR+U/HJTeAcjjJuY1fy4ISI=,tag:h/f1s1ICmsYL6RirkYXa1w==,type:str]
    port: ENC[AES256_GCM,data:zVUxvg==,iv:BB3i6ucvG24dD7djl+EFj3O9KV647ECox4ZhiZAZ7zA=,tag:JW71/D8KDM0Bpy4GTIWuvg==,type:int]
    username: ENC[AES256_GCM,data:qr/ayNOl,iv:vkxocAGHCpekpD1PBIQeACAqO6hSe5JnaLj+uPcW7E4=,tag:RIbHrxVvuK0GT8y1YevrTA==,type:str]
    password: ENC[AES256_GCM,data:fsRclkf+LhUBfBGDC37Bsj9JE8AG,iv:R/RABKVL4V3VnEMizDnu9/sbYFeruynWWcWVMVHFldo=,tag:M643DvZk/bqUZSI7zqPq6w==,type:str]
api:
    key: ENC[AES256_GCM,data:x80Y6/ykZnTHvTdTqg==,iv:63iS1tGjg+ZGdAKMX0eyLHSsfM0fCncqMFOZoHi2D5U=,tag:fURvKhe9XOrMoki38o5ZFw==,type:str]
    secret: ENC[AES256_GCM,data:TwlVHzULiowzMIUlrcMrMw==,iv:u+ciy2ajM+hOnP1QohDkfDSAPqJtiVQ7XjqQv8RateE=,tag:kFMruU43jCgX/WjPHOa92Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSnE0aHNJUmZGbmMza2ZX
            T3N4UTZmU0k0UlYvRFdkWnBYU1JHWnlPY1EwCmprRlFweWpsUUZsdy81SlBiRHdr
            eTJ1YlJsSklZK1FrUXdUQ01ERitnNUEKLS0tIFcrYVk4S0p6ZnZqMXErZHFkRXA5
            bWFnRHEyYlRVbFY1RjRtYkh4dE81bHMKLMZ8w4lay4B6cJI0rdgCgELnPV43/WVN
            jiGoR1rgEBknYpcEFxAuINnQduwAVINZtCIsVOOZ4LX4wr5KFG3Hyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jq7hcntklunzhpdr99lnf0sr93kafkww3qe5ycc70xj7yp8uu94q27rwld
    lastmodified: "2026-05-17T12:09:10Z"
    mac: ENC[AES256_GCM,data:G3nc0/p9ITPj6ph5mV+hRrLepS4vjz26qzq1f4RO8tQ0kVLyfFHbzwlG1D3nnGgCW90cI4cZF8VWu9rIDtgxFIAW1Bd3W13GmRqB1F8297eoF3aMPzsvabZOhhYk3Aio7OV27hOhAnHBSS9rdHUgfn0BEL+qacmK+DOoyXf2SNM=,iv:63Cx1SAZt5V4PSZ4qRl7Z+4xb8wOXGRck3bXDxBd2lg=,tag:40GSLBAvZ1XATTUZrMbQ/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
